import Head from 'next/head'
import { Inter } from 'next/font/google'
import { licensesVersionMap } from '@/components/licenses/License'
import Link from 'next/link'

export default function LicenseArchivePage() {
  return (
    <>
      <Head>
        <title>過去のライセンス一覧</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container mx-auto my-10 space-y-10">
        <article className="prose mx-auto">
          <h1>過去のライセンス一覧</h1>
          <ul>
            {
              Array.from(licensesVersionMap.keys()).map((version: string) => {
                return (
                  <li key={version}>
                    <Link
                      href={`/policy/archives/${version}`}
                    >
                      v{version}
                    </Link>
                  </li>
                )
              })
            }
          </ul>
        </article>
      </main>
    </>
  )
}
