import Head from 'next/head'
import License, { licensesVersionMap } from '@/components/licenses/License'
import Link from 'next/link'
import { notFound } from 'next/navigation'

export default function LicenseOfVersion({ params } : { params: { version: string }}) {
  const version = params.version
  const exists = licensesVersionMap.has(version)
  console.log(licensesVersionMap, version)
  if (!exists) {
    notFound()
  }
  return (
    <>
      <Head>
        <title>{`ナタクラゲライセンス v${version}`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container mx-auto my-10 space-y-10">
        <article className="prose mx-auto">
          <License version={version} />
          <Link href="/policy/archives">別の時点でのライセンスを見る</Link>
        </article>
      </main>
    </>
  )
}
