import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Return from '@/src/Return'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>秘密のページ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>秘密のページ</h1>
          <p>よく見つけたね！</p>
        </article>
        <Return />
      </main>
    </>
  )
}
