import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Return from '@/src/Return'
import License, { licensesVersionMap } from '@/src/licenses/License'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { notFound } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export default function LicenseOfVersion() {
  const router = useRouter()
  const { version } = router.query as { version: string }
  const exists = licensesVersionMap.has(version)
  if (router.isReady && !exists) {
    notFound()
  }
  return (
    <>
      <Head>
        <title>{`ナタクラゲライセンス v${version}`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <License version={version} />
          <Link href="/policy/archives">別の時点でのライセンスを見る</Link>
        </article>
        <Return />
      </main>
    </>
  )
}
