import Head from 'next/head'

export default function HapinessPage() {
  return (
    <>
      <Head>
        <title>幸せ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container mx-auto my-10 space-y-10">
        <h1 className="text-center text-3xl">404</h1>
        <p className="text-center">Happiness is not found in this world.</p>
      </main>
    </>
  )
}
