import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Return from '@/src/Return'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>ナタクラゲについて</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>ナタクラゲについて</h1>
          <h2>ナタクラゲとは</h2>
          <p>鉈を持ったクラゲ。体長50cmくらいだが、触手は1mくらい伸びることもある。<br />普段は空中にふよふよ浮いているが、人間を見つけるとその触手で捕まえ、鉈を振り降ろして解体してから食べる。</p>
          <p>最近はインターネットでサイバークラゲとして活動している。稀に音楽と小説を産卵する。</p>
          <h2>実績</h2>
          <ul>
            <li>YouTube登録者94人（2023/3/1時点）</li>
            <li>1億回以上の呼吸（クラゲなのに！）</li>
          </ul>
          <h2>スキル</h2>
          <ul>
            <li>ネットサーフィン</li>
            <li>ギター</li>
            <li>曲作り</li>
            <li>プログラミング</li>
              <ul>
                <li>Python🐍☻</li>
                <li>JavaScript</li>
                <li>（C++）😞</li>
              </ul>
          </ul>
          <h2>苦手なもの</h2>
          <ul>
            <li>人間</li>
            <li>インターネット</li>
            <li>SNS</li>
          </ul>
        </article>
        <Return />
      </main>
    </>
  )
}
