import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import { 
  FaYoutube,
  FaGithub,
  FaBookOpen,
  FaSoundcloud,
  
} from "react-icons/fa"
import { SiNiconico, SiPixiv } from "react-icons/si"
import { TbLetterP } from "react-icons/tb"
import Return from '@/src/Return'
import Modal from '@/src/Modal'
import { BaseSyntheticEvent, useState } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Contact() {
  const [name, setName] = useState<string>("")
  const [email, setEmail] = useState<string>("")
  const [title, setTitle] = useState<string>("")
  const [content, setContent] = useState<string>("")

  const [modalText, setModalText] = useState<string>("default")
  const [modalShowing, setModalShowing] = useState<boolean>(false)

  const showModal = (text: string, duration: number) => {
    setModalText(text)
    setModalShowing(true)
    setTimeout(() => {
      setModalShowing(false)
    }, duration)
  }

  const resetForm = () => {
    setName("")
    setEmail("")
    setTitle("")
    setContent("")
  }

  const onSubmit = async (event: BaseSyntheticEvent) => {
    event.preventDefault()
    const response = await fetch("https://docs.google.com/forms/d/e/1FAIpQLSe2kcQ3DWJSoYURIS9ARTUhymadXiJoNimGJQ7jGyCyGu76gQ/formResponse", {
      method: 'POST',
      mode: 'no-cors',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: new URLSearchParams({
        "entry.98194133": name,
        "emailAddress": email,
        "entry.823789016": title,
        "entry.1870725190": content
      })
    })
    showModal("送信しました。", 5000)
    resetForm()
  }

  return (
    <>
      <Head>
        <title>お問い合わせ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>お問い合わせ</h1>
          <h2>各種アカウント</h2>
          <div className={styles.center}>
            <ul className={styles.links}>
              <li><a 
                href="https://www.youtube.com/@natakurage"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaYoutube
                  color='red'
                />
                <span className={styles.linkName}>YouTube</span>
              </a></li>
              <li><a 
                href="http://nicovideo.jp/user/46928394"
                target="_blank"
                rel="noopener noreferrer"
              >
                <SiNiconico /><span className={styles.linkName}>ニコニコ</span>
              </a></li>
              <li><a 
                href="https://piapro.jp/icchy1128music"
                target="_blank"
                rel="noopener noreferrer"
              >
                <TbLetterP 
                  color='magenta'
                />
                <span className={styles.linkName}>Piapro</span>
              </a></li>
              <li><a 
                href="https://soundcloud.com/pbj5g2xegmae"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaSoundcloud
                  color = 'orange'
                />
                <span className={styles.linkName}>SoundCloud</span>
              </a></li>
              <li><a 
                href="https://kakuyomu.jp/users/icchy1128Novelman"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaBookOpen
                  color='skyblue'
                />
                <span className={styles.linkName}>カクヨム</span>
              </a></li>
              <li><a 
                href="https://www.pixiv.net/users/26489552"
                target="_blank"
                rel="noopener noreferrer"
              >
                <SiPixiv
                  color='blue'
                />
                <span className={styles.linkName}>Pixiv</span>
              </a></li>
              <li><a 
                href="https://github.com/UzoGaMuzol"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaGithub /><span className={styles.linkName}>GitHub</span>
              </a></li>
            </ul>
          </div>
          <h2>お問い合わせフォーム</h2>
          <p>お問い合わせは以下のフォームからお願いします。</p>
          <p>※内部でGoogleフォームを使っており、仕様変更で壊れる可能性や送信できているように見えてできていない可能性がありますので、確実に届けたい方は
            <a 
              href="https://docs.google.com/forms/d/e/1FAIpQLSe2kcQ3DWJSoYURIS9ARTUhymadXiJoNimGJQ7jGyCyGu76gQ/viewform?usp=sf_link"
              target="_blank"
              rel="noopener noreferrer"
            >こちらのリンク先</a>
            のフォームをご利用いただくか、上記のアカウントへ直接連絡してください。送信できた場合、入力されたメールアドレスに確認メールが届きます。</p>
          <div className={styles.center}>
            <form
              target="hidden-iframe"
              className={styles.customForm}
              onSubmit={onSubmit}
            >
              <div>
                <label htmlFor="form-name">お名前</label>
                <input
                  id="form-name"
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                />
              </div>
              <div>
              <label htmlFor="form-email">メールアドレス</label>
                <input
                  id="form-email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
              <div>
              <label htmlFor="form-title">件名</label>
                <input
                  id="form-title"
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  required
                />
              </div>
              <div>
              <label htmlFor="form-content">内容</label>
                <textarea
                  id="form-content"
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  rows={11}
                  required
                />
              </div>
              <div>
                <input type="submit" />
              </div>
            </form>
            <iframe name="hidden-iframe" style={{display: "none"}}></iframe>
          </div>
          <Modal
            text={modalText}
            showing={modalShowing}
          />
        </article>
        <Return />
      </main>
    </>
  )
}
