import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import { 
  FaYoutube,
  FaGithub,
  FaBookOpen,
  FaSoundcloud,
  
} from "react-icons/fa"
import { SiNiconico, SiPixiv } from "react-icons/si"
import { TbLetterP } from "react-icons/tb"
import Return from '@/src/Return'

const inter = Inter({ subsets: ['latin'] })

export default function Contact() {
  return (
    <>
      <Head>
        <title>お問い合わせ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>お問い合わせ</h1>
          <h2>各種アカウント</h2>
          <div className={styles.center}>
            <ul className={styles.links}>
              <li><a 
                href="https://www.youtube.com/channel/UCsE5FbMXnmBYe-THSt3kwJQ"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaYoutube
                  color='red'
                />
                <span className={styles.linkName}>YouTube</span>
              </a></li>
              <li><a 
                href="http://nicovideo.jp/user/46928394"
                target="_blank"
                rel="noopener noreferrer"
              >
                <SiNiconico /><span className={styles.linkName}>ニコニコ</span>
              </a></li>
              <li><a 
                href="https://piapro.jp/icchy1128music"
                target="_blank"
                rel="noopener noreferrer"
              >
                <TbLetterP 
                  color='magenta'
                />
                <span className={styles.linkName}>Piapro</span>
              </a></li>
              <li><a 
                href="https://soundcloud.com/pbj5g2xegmae"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaSoundcloud
                  color = 'orange'
                />
                <span className={styles.linkName}>SoundCloud</span>
              </a></li>
              <li><a 
                href="https://kakuyomu.jp/users/icchy1128Novelman"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaBookOpen
                  color='skyblue'
                />
                <span className={styles.linkName}>カクヨム</span>
              </a></li>
              <li><a 
                href="https://www.pixiv.net/users/26489552"
                target="_blank"
                rel="noopener noreferrer"
              >
                <SiPixiv
                  color='blue'
                />
                <span className={styles.linkName}>Pixiv</span>
              </a></li>
              <li><a 
                href="https://github.com/UzoGaMuzol"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaGithub /><span className={styles.linkName}>GitHub</span>
              </a></li>
            </ul>
          </div>
          <h2>Googleフォーム</h2>
          <p>お問い合わせは以下のフォームからお願いします。</p>
          <div className={styles.googleForm}>
            <iframe 
              data-v-b2207632=""
              src="https://docs.google.com/forms/d/e/1FAIpQLSe2kcQ3DWJSoYURIS9ARTUhymadXiJoNimGJQ7jGyCyGu76gQ/viewform?embedded=true"
              title="form"
              width="600"
              height="1000"
              style={{border:0}}
              allowFullScreen
            />
          </div>
        </article>
        <Return />
      </main>
    </>
  )
}
