import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Return from '@/src/Return'

const inter = Inter({ subsets: ['latin'] })

export default function Policy() {
  return (
    <>
      <Head>
        <title>幸せ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1>404</h1>
        <p>Happiness is not found in this world.</p>
        <Return />
      </main>
    </>
  )
}
