import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Return from '@/src/Return'

const inter = Inter({ subsets: ['latin'] })

export default function Policy() {
  return (
    <>
      <Head>
        <title>ポリシーと規約</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>ポリシーと規約</h1>
          <h2>ナタクラゲの作品について</h2>
          <em><big>All Rights Revealed.</big></em>
          <p>ナタクラゲは、自分の作品の自由な使用を許可することにより、その広範な認知を図り、かつ最終的には文化の発展に寄与したいと考えております。</p>
          <p>ナタクラゲが作成したコンテンツ（映像、画像、音楽、文章など）については、個別の記載がない場合に限り、</p>
          <ul>
            <li>作者名（「ナタクラゲ」または「千本槍みなも」）または作品のURLをわかりやすい箇所に明記し、なりすましをしない</li>
            <li>営利目的で利用する場合、利用者が法人ではない</li>
          </ul>
          <p>これらの条件を守れば、無断で一部や全部を利用すること（改変も含む）を可とします。ただし、以下に留意してください。</p>
          <ul>
            <li>著作権を放棄したわけではありません。</li>
            <li>作品を利用したことによって発生したいかなる者のいかなる不利益に関する責任も、ナタクラゲは一切負わないものとします。</li>
          </ul>
          <p>また、不明な点がある場合や、この範囲を超える利用をしたい場合はお問い合わせフォーム等から連絡ください。
            なお、この声明はあくまでナタクラゲの意向を示すものであり、コンテンツを利用した者が法的な責任を問われないことを保証するものではありません。</p>
          <p>その他、必須ではありませんが以下をご一読ください。</p>
          <ul>
            <li>上記の使用方法を守っている限り問題はありませんので、なるべく個別の問い合わせは避けてください。</li>
            <li>利用目的は自由であり、一切の制限は課しませんが、許可の趣旨である「文化のためになる」利用を心がけてください。</li>
          </ul>
          <p>以上は予告なく変更される場合がありますが、変更以前の記述に従って利用したものに関しては遡及的に適用されることはないものとします。(2024/2/10)</p>
        </article>
        <Return />
      </main>
    </>
  )
}
