import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Return from '@/src/Return'

const inter = Inter({ subsets: ['latin'] })

export default function Policy() {
  return (
    <>
      <Head>
        <title>ポリシーと規約</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>ポリシーと規約</h1>
          <h2>ナタクラゲの作品について</h2>
            <em><big>All Rights Revealed.</big></em>
            <p>ナタクラゲが作成したコンテンツ（映像、画像、音楽、文章など）については、個別の記載がない場合に限り、</p>
            <ul>
              <li>作者名（「ナタクラゲ」）または作品のURLをわかりやすい箇所に明記し、なりすましをしない</li>
              <li>営利目的で利用する場合、利用者が法人ではない</li>
            </ul>
            <p>これらの条件を守れば、無断で一部や全部を利用すること（改変も含む）を可とします。ただし、以下に留意してください。</p>
            <ul>
              <li>すべての著作権等の権利は私に帰属します。権利を放棄したわけではありません。</li>
              <li>作品を利用したことによって発生したいかなる者のいかなる不利益に関する責任も、ナタクラゲは一切負わないものとします。</li>
            </ul>
            <p>また、不明な点がある場合や、この範囲を超える利用をしたい場合はお問い合わせフォーム等から連絡ください。
              なお、この声明はあくまでナタクラゲの意向を示すものであり、コンテンツを利用した者が法的な責任を問われないことを保証するものではありません。</p>
            <p>以上は予告なく変更される場合がありますが、変更以前の記述に従って利用したものに関しては遡及的に適用されることはないものとします。(2023/3/1)</p>
        </article>
        <Return />
      </main>
    </>
  )
}
