import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import YouTubeEmbed from '@/src/YoutubeEmbed'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>秘密のページ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>“脛孝行”として</h1>
          <h2>脛孝行とは</h2>
          <p>自分をクラゲだと思い込んでいる一般大学生。世間的に見れば将来有望だが、内面はコミュ障でぼっちで自意識過剰で意識不明で自我拡散というだいぶ終わってる人。</p>
          <p>最近VOICEVOX動画をよく出している。また教祖を始めたらしい。</p>
          <h2>実績</h2>
          <ul>
            <li>YouTube登録者151人（2023/3/2時点）</li>
            <li>ニコニコレベル8</li>
            <li>1億回以上の呼吸</li>
          </ul>
          <h2>スキル</h2>
          <ul>
            <li>教祖</li>
            <li>ふざけた動画作成</li>
            <li>ふざけたWebアプリ作成</li>
          </ul>
          <h2>苦手なもの</h2>
          <ul>
            <li>喧嘩</li>
          </ul>
          <h2>動画</h2>
          <div className={styles.grid}>
            <div className={styles.card}>
              <YouTubeEmbed vid="dRT8ilMXkgg" width={300}></YouTubeEmbed>
              <h3 className={inter.className}>
                ゲーミングずんだもん
              </h3>
              <p className={styles.description}>
                YouTubeで一番再生されているので一応載せましたが、正直ただの運なので見る価値はないです。
              </p>
            </div>
            <div
              className={styles.card}
            >
              <YouTubeEmbed vid="q0vFZ0zrOzg" width={300}></YouTubeEmbed>
              <h3 className={inter.className}>
                ずんだもんと学ぶ小便器の正しいマナー
              </h3>
              <p className={styles.description}>
                Urinal Etiquetteという海外ミームを参考に作りました。サイレントですがかなり伸びました。下品なので恐縮です。
              </p>
            </div>
            <div
              className={styles.card}
            >
              <YouTubeEmbed vid="x_zsZFAmbDo" width={300}></YouTubeEmbed>
              <h3 className={inter.className}>
                群れになって泳ぐずんだもん
              </h3>
              <p className={styles.description}>
                Boidという群れを表現できるアルゴリズムがあって、それを実装して作りました。Webアプリとしても公開したので見てみてください。
              </p>
            </div>
            <div
              className={styles.card}
            >
              <YouTubeEmbed vid="B1T13pI3Hxo" width={300}></YouTubeEmbed>
              <h3 className={inter.className}>
                ずんだもんと見るバカ #Shorts
              </h3>
              <p className={styles.description}>
                結構初期に出して、まだコメントが付く息が長い動画です。序盤のギミックが印象的過ぎたせいか、真のオチであるラストの意図に気が付く人がほとんどいなかったのは反省点です。
              </p>
            </div>
            <div
              className={styles.card}
            >
              <YouTubeEmbed vid="6mlA3WQNhz8" width={300}></YouTubeEmbed>
              <h3 className={inter.className}>
                ずんだもんBB?+使用例
              </h3>
              <p className={styles.description}>
                再生数が際立って多いわけではありませんが、思い入れがあるので載せました。実は風刺的な意図があるのですが、ただの不気味な動画だと思っていただければそれで結構です。
              </p>
            </div>
          </div>
          <div className={styles.grid}>
            <div className={styles.card}>
              <a href="https://zunda-boid.web.app">
                <h3 className={inter.className}>
                  群れになって泳ぐずんだもん
                </h3>
                <p>https://zunda-boid.web.app</p>
                <p className={styles.description}>
                  動画でも取り上げたBoidをP5.jsで実装したものです。
                  オリジナルはPython+PyGameでしたが、WebアプリにするにあたってP5.jsに移植しました。
                  （このサイトの背景もBoidです。）
                </p>
              </a>
            </div>
            <div className={styles.card}>
              <a href="https://zunda-bound.web.app">
                <h3 className={inter.className}>
                  ぽよぽよずんだもん
                </h3>
                <p>https://zunda-bound.web.app</p>
                <p className={styles.description}>
                  モーションセンサーを使ってずんだもんが画面を滑り回るというものです。
                  今のところAndroidでしか動きませんが。
                  動きが早いと驚き、壁にぶつかると跳ねるようにしました。
                </p>
              </a>
            </div>
          </div>
        </article>
        <Link
            href="/"
            className={styles.card}
        >
          <h2 className={inter.className}>
          トップに戻る
          </h2>
        </Link>
      </main>
    </>
  )
}
