import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Std.module.css'
import Link from 'next/link'
import YouTubeEmbed from '@/src/YoutubeEmbed'
import Return from '@/src/Return'
import Card from '@/src/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Works() {
  const musicWorks = [
      {
        vid: "69s14zGHevU",
        title: "ナタクラゲ",
        content: "森の中に、不思議な格好をしたかわいらしい少女がいた。"
          + "近寄ってみると、突然鉈を持って襲いかかってきた。"
          + "彼女は街や海に繰り出し、人々を次々に殺して回る。"
          + "まるで、何かの鬱憤を晴らすかのように。"
      },
      {
        vid: "ZvNJcR_AuX8",
        title: "シロップ",
        content: "乾いた心は、粘り気を帯びて、そのまま干からびていく。"
      },
      {
        vid: "zF7bAz8IelU",
        title: "懲役80年",
        content: "少女は、物心ついた頃から実験施設に監禁されていた。"
          + "実験や雑居房での苦しみの日々――。"
      },
      {
        vid: "RHSTOALaNJw",
        title: "沈んでゆく",
        content: "底のない闇へ、沈んでゆく――。"
      }
  ]
  const movieWorks = [
    {
      vid: "ThX-p6wxrC4",
      title: "まもなく、4番線に、\"死\"がまいります。",
      content: ""
    }
  ]
  return (
    <>
      <Head>
        <title>作品</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <article>
          <h1>作品</h1>
          <h2>音楽（クリックで再生）</h2>
          <div className={styles.grid}>
            {
              musicWorks.map((work) => (
                <div key={work.vid} >
                  <YouTubeEmbed vid={work.vid} />
                  <Card
                    title={work.title}
                    content={work.content}
                  />
                </div>
              ))
            }
          </div>
          <h2>映像作品（クリックで再生）</h2>
          <div className={styles.grid}>
          {
              movieWorks.map((work) => (
                <div key={work.vid} >
                  <YouTubeEmbed vid={work.vid} />
                  <Card
                    title={work.title}
                    content={work.content}
                  />
                </div>
              ))
            }
          </div>
          <Link
            href="/secret"
            className={styles.secretLink}
          >&nbsp;</Link>
        </article>
        <Return />
      </main>
    </>
  )
}
